Repository MolSSI/QCEngine, pull requests merged in 2019-08, with the labels that each got.

#116 Compute: Environments
  qcengine/compute.py
  qcengine/testing.py
  qcengine/tests/test_config.py
  qcengine/util.py
Labels: Enhancement

#117 Extras passthrough
  qcengine/programs/dftd3.py
  qcengine/programs/mopac.py
  qcengine/programs/mp2d.py
  qcengine/tests/test_procedures.py
  qcengine/tests/test_standard_suite.py
Labels: Enhancement

#120 MSGPack updates
  devtools/conda-envs/psi-nightly.yaml
  devtools/conda-envs/psi.yaml
  devtools/conda-envs/rdkit.yaml
  devtools/conda-envs/torchani.yaml
  qcengine/procedures/geometric.py
  qcengine/programs/psi4.py
  qcengine/tests/test_procedures.py
  qcengine/tests/test_program_utils.py
  qcengine/tests/test_standard_suite.py
  setup.py
Labels: Enhancement

#137 Enable Azure CI with custom images for proprietary code
  .azure-pipelines.yml
  devtools/azure_ci_images.md
  devtools/conda-envs/base.yaml
Labels: Feature, Testing

#138 Update changelog to test the Azure triggers
  devtools/azure_ci_images.md
  docs/source/changelog.rst
Labels: Testing

#139 Update the install docs
  docs/source/install.rst
Labels: Documentation

#141 Changelog v0.10.0
  docs/source/changelog.rst
  docs/source/community.rst
  docs/source/dev_guidelines.rst
  docs/source/index.rst
Labels: Documentation
