Repository MolSSI/QCEngine, pull requests merged in 2019-05, with the labels that each got.

#65 Torchani Update
  README.md
  devtools/conda-envs/torchani.yaml
  docs/source/community.rst
  docs/source/index.rst
  docs/source/single_compute.rst
  qcengine/programs/__init__.py
  qcengine/programs/executor.py
  qcengine/programs/mp2d.py
  qcengine/programs/psi4.py
  qcengine/programs/rdkit.py
  qcengine/programs/terachem.py
  qcengine/programs/tests/test_programs.py
  qcengine/programs/torchani.py
  qcengine/tests/test_procedures.py
  qcengine/tests/test_standard_suite.py
  qcengine/util.py
Labels: Enhancement

#69 Custom Exceptions
  qcengine/__init__.py
  qcengine/compute.py
  qcengine/exceptions.py
  qcengine/procedures/base.py
  qcengine/procedures/geometric.py
  qcengine/programs/__init__.py
  qcengine/programs/dftd3/dashparam.py
  qcengine/programs/dftd3/runner.py
  qcengine/programs/mp2d.py
  qcengine/programs/psi4.py
  qcengine/programs/rdkit.py
  qcengine/programs/terachem.py
  qcengine/programs/tests/test_dftd3.py
  qcengine/programs/tests/test_programs.py
  qcengine/programs/torchani.py
  qcengine/tests/test_program_utils.py
  qcengine/tests/test_standard_suite.py
  qcengine/util.py
Labels: Enhancement, Feature

#71 Molpro can now be run by QCEngine
  qcengine/programs/molpro.py
  qcengine/programs/tests/test_molpro.py
  qcengine/programs/tests/test_terachem.py
  qcengine/testing.py
Labels: Enhancement, Feature

#74 Travis: Removes caching and reduces pytorch overhead
  .travis.yml
  devtools/conda-envs/psi-nightly.yaml
  devtools/conda-envs/psi.yaml
  devtools/conda-envs/torchani.yaml
Labels: Testing

#73 half a Cfour interface
  .codecov.yml
  qcengine/programs/cfour/__init__.py
  qcengine/programs/cfour/harvester.py
  qcengine/programs/cfour/runner.py
  qcengine/programs/util/__init__.py
  qcengine/programs/util/hessparse.py
Labels: Feature
