Repository MolSSI/QCEngine, pull requests merged in 2019-02, with the labels that each got.

#24 Improve load times
  qcengine/config.py
  qcengine/programs/psi4.py
Labels: Enhancement

#25 Minor Cleanups
  docs/source/changelog.rst
  qcengine/_version.py
  qcengine/compute.py
  qcengine/programs/psi4.py
  qcengine/programs/rdkit.py
  qcengine/programs/torchani.py
  qcengine/testing.py
  qcengine/tests/addons.py
  qcengine/tests/test_compute.py
  qcengine/tests/test_config.py
  qcengine/tests/test_procedures.py
  qcengine/units.py
  qcengine/util.py
  setup.cfg
Labels: Enhancement

#30 Psi4: Ensures output always goes to stdout field
  devtools/conda-envs/psi.yaml
  devtools/conda-envs/rdkit.yaml
  devtools/conda-envs/torchani.yaml
  docs/source/changelog.rst
  qcengine/programs/psi4.py
  qcengine/tests/test_compute.py
  qcengine/util.py
  setup.py
Labels: Computation, Enhancement

#31 Example: Updates the example script
  examples/Examples.ipynb
Labels: Enhancement

#32 Create common execution function
  .travis.yml
  qcengine/compute.py
  qcengine/config.py
  qcengine/programs/__init__.py
  qcengine/programs/dftd3/__init__.py
  qcengine/programs/dftd3/dashparam.py
  qcengine/programs/dftd3/runner.py
  qcengine/programs/dftd3/util.py
  qcengine/programs/executor.py
  qcengine/programs/intf_dftd3/worker.py
  qcengine/programs/psi4.py
  qcengine/programs/rdkit.py
  qcengine/programs/tests/test_dftd3.py
  qcengine/programs/torchani.py
  qcengine/testing.py
  qcengine/tests/addons.py
  qcengine/tests/test_compute.py
  qcengine/tests/test_config.py
  qcengine/tests/test_procedures.py
  qcengine/util.py
Labels: Enhancement

#34 Model Update
  qcengine/compute.py
  qcengine/programs/psi4.py
  qcengine/tests/test_compute.py
  qcengine/tests/test_procedures.py
  qcengine/util.py
Labels: Enhancement

#35 CI: Pull pytorch-cpu to avoid pulling CUDA in CI
  devtools/conda-envs/torchani.yaml
  devtools/conda-recipe/meta.yaml
Labels: Testing

#36 v0.6 release tweaks
  .gitignore
  README.md
  docs/source/api.rst
  docs/source/changelog.rst
  docs/source/community.rst
  docs/source/conf.py
  docs/source/environment.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/single_compute.rst
  qcengine/__init__.py
  qcengine/compute.py
  qcengine/config.py
  qcengine/extras.py
  qcengine/programs/__init__.py
  qcengine/programs/dftd3/dashparam.py
  qcengine/programs/dftd3/runner.py
  qcengine/programs/dftd3/util.py
  qcengine/programs/executor.py
  qcengine/programs/molpro.py
  qcengine/programs/psi4.py
  qcengine/programs/rdkit.py
  qcengine/programs/tests/test_dftd3.py
  qcengine/programs/tests/test_molpro.py
  qcengine/programs/tests/test_programs.py
  qcengine/programs/torchani.py
  qcengine/stock_mols.py
  qcengine/testing.py
  qcengine/tests/test_procedures.py
  qcengine/tests/test_program_utils.py
  qcengine/tests/test_standard_suite.py
  qcengine/util.py
Labels: Computation, Enhancement
