Repository MolSSI/QCEngine, pull requests merged in 2019-07, with the labels that each got.

#99 Psi4 Scratch Control
  qcengine/programs/psi4.py
  qcengine/programs/tests/test_dftd3_mp2d.py
Labels: Enhancement

#102 DFTD3: Errors are now correctly a FailedOperation
  devtools/conda-envs/psi-nightly.yaml
  devtools/conda-envs/psi.yaml
  devtools/conda-envs/rdkit.yaml
  devtools/conda-envs/torchani.yaml
  qcengine/programs/dftd3.py
  setup.py
Labels: Bug, Enhancement

#100 Mopac
  qcengine/programs/base.py
  qcengine/programs/model.py
  qcengine/programs/molpro.py
  qcengine/programs/mopac.py
  qcengine/programs/tests/test_molpro.py
  qcengine/programs/tests/test_programs.py
  qcengine/testing.py
  qcengine/tests/test_procedures.py
Labels: Feature

#108 Update changelog for 0.8.0
  docs/source/changelog.rst
Labels: Documentation

#109 Ensures Geometric will correctly retry gradient evaluations
  qcengine/procedures/geometric.py
  qcengine/programs/tests/test_programs.py
  qcengine/testing.py
  qcengine/tests/test_procedures.py
Labels: Bug

#111 0.8.1 patch docs
  docs/source/changelog.rst
Labels: Documentation

#114 0.8.2 Docs and bugfix for required kwargs in Fractal's stack
  docs/source/changelog.rst
  qcengine/compute.py
Labels: Bug, Computation
