Repository MolSSI/QCEngine, pull requests merged in 2022-06, with the labels that each got.

#350 Updated docstrings and function annotations for compute and compute_procedure
  docs/source/environment.rst
  docs/source/index.rst
  qcengine/compute.py
  qcengine/config.py
  qcengine/programs/model.py
  qcengine/programs/tests/test_canonical_config.py
  qcengine/programs/tests/test_canonical_fields.py
  qcengine/tests/test_config.py
  qcengine/util.py
Labels: Documentation

#353 Added TeraChemFrontEndHarness. Refactored TeraChemPBSHarness share co…
  qcengine/programs/base.py
  qcengine/programs/terachem_frontend.py
  qcengine/programs/terachem_pbs.py
Labels: Feature

#333 Allow NWChem to restart single-point computations
  qcengine/procedures/nwchem_opt/__init__.py
  qcengine/programs/nwchem/runner.py
  qcengine/programs/tests/test_nwchem.py
Labels: Bug
