Repository MolSSI/QCEngine, pull requests merged in 2022-07, with the labels that each got.

#349 Hessian parsing fixes for Turbomole Harness
  qcengine/programs/tests/test_turbomole.py
  qcengine/programs/turbomole/harvester.py
  qcengine/programs/turbomole/runner.py
Labels: Bug

#364 gradients with ghost atoms for cfour and nwchem
  qcengine/programs/cfour/harvester.py
  qcengine/programs/nwchem/harvester.py
  qcengine/programs/nwchem/runner.py
  qcengine/programs/tests/test_ghost.py
Labels: Enhancement

#363 dir structure in execute and properties in Cfour
  qcengine/programs/cfour/germinate.py
  qcengine/programs/cfour/runner.py
  qcengine/tests/test_procedures.py
  qcengine/util.py
Labels: Enhancement

#343 Implement harness for DFT-D3 Python API
  devtools/conda-envs/xtb.yaml
  docs/source/program_overview.rst
  qcengine/programs/base.py
  qcengine/programs/dftd4.py
  qcengine/programs/dftd_ng.py
  qcengine/programs/empirical_dispersion_resources.py
  qcengine/programs/tests/test_sdftd3.py
  qcengine/testing.py
Labels: Feature

#372 mopac ci lane. pin to qcel 0.25
  devtools/conda-envs/opt-disp.yaml
  qcengine/programs/mopac.py
  qcengine/programs/tests/test_programs.py
  qcengine/tests/test_procedures.py
  setup.py
Labels: Testing

#368 WIP: 0.24 changelog
  README.md
  docs/source/changelog.rst
Labels: Documentation
